FROM apache/airflow:3.3.1-python3.13

USER root

WORKDIR /opt/airflow/project

COPY requirements.txt /tmp/requirements.txt

USER airflow

RUN pip install --no-cache-dir -r /tmp/requirements.txt

USER root

COPY . /opt/airflow/project

USER airflow